project: 
  type: website
  
website: 
  page-navigation: true
  back-to-top-navigation: true
  title: "Analysts' Guide"
  site-url: "https://dfe-analytical-services.github.io/analysts-guide"
  repo-url: https://github.com/dfe-analytical-services/analysts-guide
  repo-actions: [edit, issue]
  google-analytics: "G-KBJCBD114T"
  cookie-consent: 
    style: headline
    palette: dark

  page-footer:
    right: "This page is maintained by statistics.development@education.gov.uk"
    left: "Department for Education, 2024"
  
  search:
    location: navbar
    type: textbox
    
  sidebar:
    logo: "images/duck_guidance.png" 
    pinned: true
    align: center
    tools:
      - icon: envelope
        href: mailto:statistics.development@education.gov.uk
        text: "Email us"
      - icon: microsoft-teams
        menu: 
          - text: "DfE analysts network"
            href: https://teams.microsoft.com/l/team/19%3a50f82a2718184a0e98ba86c3d411a02f%40thread.skype/conversations?groupId=6572094f-43a3-4537-bcf0-fc27dc6557ed&tenantId=fad277c9-c60a-4da1-b5f3-b3b8b34a82f9
            target: _blank
          - text: "Statistics production"
            href: https://teams.microsoft.com/l/team/19%3ae3c8551e86094e259a60848fcff4dbc1%40thread.skype/conversations?groupId=679b2376-8c8c-4062-a1c9-0744ce5ac88f&tenantId=fad277c9-c60a-4da1-b5f3-b3b8b34a82f9
            target: _blank
          - text: "DfE R community"
            href: https://teams.microsoft.com/l/team/19%3a311ec2e4d46b4dd38f0d61f05fb93383%40thread.skype/conversations?groupId=b95c605d-8fbc-4e4d-9a76-2f7d1c55e70a&tenantId=fad277c9-c60a-4da1-b5f3-b3b8b34a82f9
            target: _blank
            
      - icon: camera-reels
        menu:
          - href: https://educationgovuk.sharepoint.com/:f:/r/sites/lvewp00086/SSU%20%20open%20sharing/Statistician%27s%20Guide%20to%20the%20Galaxy?csf=1&web=1&e=owScaj
            target: _blank
            text: "Guide to the Galaxy sessions"
          - href: https://educationgovuk.sharepoint.com/:f:/r/sites/lvewp00086/SSU%20%20open%20sharing/Explore%20Education%20Statistics?csf=1&web=1&e=HVpi0D
            target: _blank
            text: "EES show and tells"
          - href: https://educationgovuk.sharepoint.com/:f:/r/sites/lvewp00086/SSU%20%20open%20sharing/Reproducible%20Analytical%20Pipeline%20(RAP)%20resources/Knowledge-share%20series?csf=1&web=1&e=H0pcSH
            target: _blank
            text: "RAP knowledge share series"
          - href: https://educationgovuk.sharepoint.com/sites/sarpi/g/AC/Coffee%20and%20Coding.aspx?xsdata=MDV8MDF8fGU5YTkwYWU1OTNiNjQzZTIyZTM2MDhkYjVhY2MxN2JlfGZhZDI3N2M5YzYwYTRkYTFiNWYzYjNiOGIzNGE4MmY5fDB8MHw2MzgyMDM2MDQ4MjEyMjUwMTR8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPbTFsWlhScGJtZGZXVlJuZUUxRVVUTlphbGwwVGpKUk1FNTVNREJhYW1zMVRGUnJNbHBYV1hSTmVtTjZXbXBCTWxwdFZUQlBWMVV3UUhSb2NtVmhaQzUyTWk5dFpYTnpZV2RsY3k4eE5qZzBOell6TmpneE5qRXh8YjdlZWE0MGYzNDg5NGYxYzJlMzYwOGRiNWFjYzE3YmV8MmE3NzU1YzRmOWMyNDZlOTkwYWVmMjlkZjY5NjczZWE%3D&sdata=ajlKYUZuNHFyNU9XSm5WR3ZZaUZHZDB4bjVJYkJzRFZNc0U1Uit5V1Q5cz0%3D&ovuser=fad277c9%2Dc60a%2D4da1%2Db5f3%2Db3b8b34a82f9%2CTess%2EWILLIAMS%40EDUCATION%2EGOV%2EUK&OR=Teams%2DHL&CT=1684763684990&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA0MDIwMjcwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D
            target: _blank
            text: "Coffee and coding sessions"            
            
      - icon: graph-up
        href: https://explore-education-statistics.service.gov.uk/
        target: _blank
        text: "Explore education statistics"
        
      - icon: github
        menu:
          - href: https://github.com/dfe-analytical-services/analysts-guide
            target: _blank
            text: "Source code"
          - href: https://github.com/dfe-analytical-services/analysts-guide/issues/new
            target: _blank
            text: "Suggest changes"
            
    style: floating
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: "Learning resources"
        contents:
          - learning-development/learning-support.qmd
          - learning-development/sql.qmd
          - learning-development/r.qmd
          - learning-development/git.qmd
          - learning-development/python.qmd
          - learning-development/datacamp-tracks.qmd
          - ADA/ada.qmd
          - ADA/databricks_fundamentals.qmd
          - ADA/databricks_notebooks.qmd
          - ADA/databricks_workflows.qmd
          - learning-development/accessibility.qmd
      - section: "Statistics production"
        contents:
          - statistics-production/pub.qmd
          - RAP/rap-statistics.qmd
          - statistics-production/ud.qmd
          - statistics-production/api-data-standards.qmd
          - statistics-production/ees.qmd
          - statistics-production/examples.qmd
          - statistics-production/embedded-charts.qmd
          - statistics-production/scrums.qmd
          - statistics-production/user-eng.qmd
          - statistics-production/user-analytics.qmd
      - section: "Writing and visualising"
        contents:
          - writing-visualising/dashboards.qmd
          - writing-visualising/dashboards_rshiny.qmd
          - writing-visualising/visualising.qmd
          - writing-visualising/writing.qmd
      - section: "Reproducible Analytical Pipelines (RAP)"
        contents: 
          - RAP/getting-started-with-rap.qmd
          - RAP/rap-expectations.qmd
          - RAP/rap-statistics.qmd
          - RAP/rap-analysis.qmd
          - RAP/rap-support.qmd
          - RAP/rap-faq.qmd
          - RAP/rap-case-studies.qmd
      - section: "Databricks Setup Guides"

      - section: "ADA and Databricks"
        contents:
          - ADA/databricks_rstudio_sql_warehouse.qmd
          - ADA/databricks_rstudio_personal_cluster.qmd
          - ADA/databricks_rstudio_personal_cluster_sparklyr_archive.qmd
          - ADA/git_databricks.qmd
          - ADA/databricks_workflow_script_databricks.qmd
          - ADA/databricks_workflow_script_rstudio.qmd

format:
  html:
    theme:
      dark:  [cyborg,theme-dark.scss]
      light: [united,theme-light.scss]
    code-copy: true
    css: styles.css
    grid: 
      sidebar-width: 370px
      body-width: 770px
      gutter-width:	2em
    highlight-style: 
      dark: printing-dark.theme
      light: printing-light.theme
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - newpagelink.lua
  - quarto
  

