name: Publication test
on: push

jobs:
  Alt-text-test:
    name: Alt-text test
    runs-on: ubuntu-latest
	defaults:
		run:
			shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Perform the alt-text test
        run: ./.github/workflows/workflow_scripts/alt-text-checker.sh